# Generated by Django 2.2.12 on 2020-06-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagline',
            field=models.CharField(default='The default', max_length=200),
            preserve_default=False,
        ),
    ]
